; PlatformIO Project Configuration File
; HAButton — ESP32-C3 Super Mini + MQTT Home Assistant

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.1

board_build.flash_mode = qio
board_build.partitions = default.csv
